### ISSUE TITLE
alarm + variables = incorrect beginning of sentence

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#572] opened 2019-04-30 22:29 UTC
When setting the float value to an `alarm` statement, both the CLI and GUI complain if the value is passed as a variable.
E.g.
```
%var: foo 10
%mod: alarm foo [true] do $SNAPSHOT ;
```
```
1/1[model.ka] Incorrect beginning of sentence 
```

**Comment by pirbo** [comment] 2019-05-02 11:13
Duplicate of #533

**Closed by pirbo** 2019-05-02 11:13 UTC
Labels: KaSim, minor bug
